language: python

python: 
  - "3.7"
  - "3.9"

install: 
  - pip install -e .
  - pip install coverage

script: 
  - pytest
  - python3 tests/doctest_runner.py

after_success: 
  - coverage run -m pytest
  - bash <(curl -s https://codecov.io/bash -t a845d1bb-a8fc-492c-80f3-9489d256edd4) 