COLOR_DICT = {
	"Gris": "Grey",
	"Grisâtre": "Greyish",
	"Blanche": "White",
	"Blanchâtre": "Whitish",
	"Blanc": "White",
	"Noir": "Black",
	"Noirâtre": "Blackish",
	"Brun": "Brown",
	"Brunâtre": "Brownish",
	"Roux": "Ginger",
	"Rouge": "Red",
	"Bleuté": "Bluish",
	"Bleuâtre": "Bluish",
	"Jaune": "Yellow",
	"Orange": "Orange",
	"Vert": "Green",
	"Verdâtre": "Greenish",
	"Olive": "Olive",
	"Olivâtre": "Olive",
	"Chataîgne": "Chestnut",
	"Bouton d'Or": "Buttercup",
	"Foncé": "Dark",
	"Bronzé": "Bronzed",
	"Violacé": "Purplish",
	"Rose": "Pink",
	"Émeraude": "Emerald",
	"Ardoisé": "Slate",
	"Carmin": "Carmine",
	"Clair": "Light",
	"Pâle": "Pale"
}